apiVersion: v1
kind: Service
metadata:
  name: tukano-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: tukano-service
# the url is -> http://tukano-service:8081/