apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: blob-service
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: blob-service
      template:
        metadata:
          labels:
            app: blob-service
        spec:
          nodeSelector:
            "kubernetes.io/os": linux
          containers:
            - name: blob-service
              image: ghcr.io/azure-samples/aks-store-demo/order-service:latest
              ports:
                - containerPort: 8080
              env:
                - name: ORDER_QUEUE_HOSTNAME
                  value: "rabbitmq"
                - name: ORDER_QUEUE_PORT
                  value: "5672"
                - name: ORDER_QUEUE_USERNAME
                  value: "username"
                - name: ORDER_QUEUE_PASSWORD
                  value: "password"
                - name: ORDER_QUEUE_NAME
                  value: "orders"
                - name: FASTIFY_ADDRESS
                  value: "0.0.0.0"
              resources:
                requests:
                  cpu: 1m
                  memory: 50Mi
                limits:
                  cpu: 75m
                  memory: 128Mi
              startupProbe:
                httpGet:
                  path: /health
                  port: 3000
                failureThreshold: 5
                initialDelaySeconds: 20
                periodSeconds: 10
              readinessProbe:
                httpGet:
                  path: /health
                  port: 3000
                failureThreshold: 3
                initialDelaySeconds: 3
                periodSeconds: 5
              livenessProbe:
                httpGet:
                  path: /health
                  port: 3000
                failureThreshold: 5
                initialDelaySeconds: 3
                periodSeconds: 3
          initContainers:
            - name: wait-for-rabbitmq
              image: busybox
              command: [ 'sh', '-c', 'until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;' ]
              resources:
                requests:
                  cpu: 1m
                  memory: 50Mi
                limits:
                  cpu: 75m
                  memory: 128Mi

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: postgres-volume
      labels:
        type: local
        app: postgres
    spec:
      storageClassName: manual
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteMany
      hostPath:
        path: /data/postgresql