apiVersion: v1
kind: Service
metadata:
  name: blob-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: blob-service
# the url is -> http://blob-service:8080/